animesuki/media/api/urls.py
"""AnimeSuki Media API URLs"""

from django.urls import path

from rest_framework.urlpatterns import format_suffix_patterns

from .views import (MediaListAPIView, MediaRetrieveAPIView, MediaArtworkListAPIView, MediaArtworkRetrieveAPIView)


urlpatterns = [
    path('<int:pk>', MediaRetrieveAPIView.as_view(), name='media-detail'),
    path('', MediaListAPIView.as_view()),
    path('artwork/<int:pk>', MediaArtworkRetrieveAPIView.as_view(), name='mediaartwork-detail'),
    path('artwork/', MediaArtworkListAPIView.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

animesuki/media/urls.py
"""AnimeSuki Media URLs"""

from django.urls import path

from .views import (MediaDetailView, MediaCreateView, MediaUpdateView, MediaArtworkView)


app_name = 'media'
urlpatterns = [
    path('<int:pk>/<slug:slug>', MediaDetailView.as_view(), name='detail'),
    path('<int:pk>/<slug:slug>/edit', MediaUpdateView.as_view(), name='update'),
    path('<int:pk>/<slug:slug>/artwork', MediaArtworkView.as_view(), name='artwork'),
    path('create', MediaCreateView.as_view(), name='create'),
]

animesuki/urls.py
"""AnimeSuki URL Configuration"""

from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView, TemplateView
from django.contrib import admin

from allauth.account import views as account


api_v1_patterns = [
    re_path(r'media/', include('animesuki.media.api.urls')),
]

# URLs for django-allauth/account have been redefined here to remove the ending slash
account_patterns = [
    path('signup', account.signup, name='account_signup'),
    path('login', account.login, name='account_login'),
    path('logout', account.logout, name='account_logout'),
    path('password/change', account.password_change, name='account_change_password'),
    path('password/set', account.password_set, name='account_set_password'),
    path('inactive', account.account_inactive, name='account_inactive'),
    # E-mail
    path('email', account.email, name='account_email'),
    path('confirm-email', account.email_verification_sent, name='account_email_verification_sent'),
    re_path(r'confirm-email/(?P<key>[-:\w]+)', account.confirm_email, name='account_confirm_email'),
    # Password reset
    path('password/reset', account.password_reset, name='account_reset_password'),
    path('password/reset/done', account.password_reset_done, name='account_reset_password_done'),
    re_path(r'password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)', account.password_reset_from_key,
            name='account_reset_password_from_key'),
    path('password/reset/key/done', account.password_reset_from_key_done, name='account_reset_password_from_key_done'),
    # No profile page at the moment
    path('profile', RedirectView.as_view(url='/'), name='account_profile'),
]

urlpatterns = [
    re_path(r'^(?P<mediatype>media|anime|manga|novel)/', include('animesuki.media.urls')),
    path('history/', include('animesuki.history.urls')),
    path('v1/', include(api_v1_patterns), name='api_v1'),
    path('admin/', admin.site.urls),
    path('account/', include(account_patterns)),
    path('', TemplateView.as_view(template_name='frontpage.html'), name='frontpage')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))] + \
                   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

animesuki/media/models.py
"""AnimeSuki Media models"""

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from animesuki.core.models import ArtworkModel
from animesuki.core.utils import DatePrecision
from animesuki.history.models import HistoryModel


class Media(HistoryModel):
    class Type:
        ANIME = 1
        MANGA = 2
        NOVEL = 3
        choices = (
            (ANIME, 'Anime'),
            (MANGA, 'Manga'),
            (NOVEL, 'Novel'),
        )

    class SubType:
        UNKNOWN = 0
        # Anime
        TV = 1
        OVA = 2
        MOVIE = 3
        WEB = 4
        SPECIAL = 5
        MUSIC = 6
        # Manga
        MANGA = 7
        MANHUA = 8
        MANHWA = 9
        WEB_MANGA = 10
        ONE_SHOT = 11
        DOUJIN = 12
        # Novel
        LIGHT_NOVEL = 13
        WEB_NOVEL = 14
        NOVEL = 15
        choices = (
            (UNKNOWN, 'Unknown'),
            ('Anime', (
                (TV, 'TV'),
                (OVA, 'OVA'),
                (MOVIE, 'Movie'),
                (WEB, 'Web'),
                (SPECIAL, 'Special'),
                (MUSIC, 'Music'),
            )),
            ('Manga', (
                (MANGA, 'Manga'),
                (MANHUA, 'Manhua'),
                (MANHWA, 'Manhwa'),
                (WEB_MANGA, 'Web Manga'),
                (ONE_SHOT, 'One Shot'),
                (DOUJIN, 'Doujin'),
            )),
            ('Novel', (
                (LIGHT_NOVEL, 'Light Novel'),
                (WEB_NOVEL, 'Web Novel'),
                (NOVEL, 'Novel'),
            ))
        )

    class Status:
        AUTO = 1
        HIATUS = 2
        CANCELLED = 3
        choices = (
            (AUTO, 'Automatic'),
            (HIATUS, 'On Hiatus'),
            (CANCELLED, 'Cancelled')
        )

    class Season:
        WINTER = 1
        SPRING = 2
        SUMMER = 3
        FALL = 4
        choices = (
            (WINTER, 'Winter'),
            (SPRING, 'Spring'),
            (SUMMER, 'Summer'),
            (FALL, 'Fall')
        )

    title = models.CharField('title', max_length=250, blank=True)
    media_type = models.PositiveSmallIntegerField('type', choices=Type.choices, default=Type.ANIME)
    sub_type = models.PositiveSmallIntegerField('sub Type', choices=SubType.choices, default=SubType.UNKNOWN)
    status = models.PositiveSmallIntegerField('status', choices=Status.choices, default=Status.AUTO)
    is_adult = models.BooleanField('r-18', default=False)
    episodes = models.IntegerField('episodes', null=True, blank=True)
    duration = models.IntegerField('duration', null=True, blank=True)
    volumes = models.IntegerField('volumes', null=True, blank=True)
    chapters = models.IntegerField('chapters', null=True, blank=True)
    start_date = models.DateField('start date', null=True, blank=True)
    start_precision = models.PositiveSmallIntegerField('precision', choices=DatePrecision.choices,
                                                       default=DatePrecision.FULL)
    end_date = models.DateField('end date', null=True, blank=True)
    end_precision = models.PositiveSmallIntegerField('precision', choices=DatePrecision.choices,
                                                     default=DatePrecision.FULL)
    season_year = models.IntegerField('season year', null=True, blank=True)
    season = models.PositiveSmallIntegerField('season', choices=Season.choices, null=True, blank=True)
    description = models.TextField('description', blank=True)
    synopsis = models.TextField('synopsis', blank=True)
    artwork_active = models.ForeignKey('MediaArtwork', related_name='media_artwork', on_delete=models.SET_NULL,
                                       null=True, blank=True, default=None)

    HISTORY_MODERATE_FIELDS = ('title', 'media_type', 'sub_type', 'is_adult')

    def __str__(self):
        return self.title

    def get_status(self):
        if self.status != self.Status.AUTO:
            return self.get_status_display()
        status = {
            self.Type.ANIME: {
                'future': 'Not yet aired',
                'present': 'Currently airing',
                'past': 'Finished'
            },
            self.Type.MANGA: {
                'future': 'Not yet published',
                'present': 'Currently publishing',
                'past': 'Finished'
            },
        }
        status[self.Type.NOVEL] = status[self.Type.MANGA]
        now = timezone.now().date()
        if self.end_date and self.end_date <= now:
            return status[self.media_type]['past']
        elif not self.start_date or self.start_date > now:
            return status[self.media_type]['future']
        else:
            return status[self.media_type]['present']

    def get_absolute_url(self, view='media:detail'):
        return reverse(view, args=[slugify(self.get_media_type_display()), self.pk, slugify(self.title)])

    class Meta:
        db_table = 'media'
        verbose_name_plural = 'media'


class MediaArtwork(ArtworkModel):
    media = models.ForeignKey(Media, on_delete=models.PROTECT)

    ARTWORK_FOLDER = 'media'
    ARTWORK_SIZES = ((75, 75, 't75'), (150, 150, 't150'), (225, 225, 't225'), (450, 450, 't450'),
                     (292, 600, '292w'), (352, 800, '352w'), (438, 1000, '438w'),
                     (528, 1200, '528w'), (584, 1200, '584w'), (704, 1400, '704w'))

    def sub_folder(self):
        return self.media.pk

    class Meta:
        db_table = 'media_artwork'

animesuki/media/forms.py
"""AnimeSuki Media forms"""

from django import forms

from .models import Media, MediaArtwork


class MediaCreateForm(forms.ModelForm):
    comment = forms.CharField(label='Comment / Source')

    class Meta:
        model = Media
        fields = ['title', 'media_type', 'sub_type', 'status', 'is_adult',
                  'episodes', 'duration', 'volumes', 'chapters',
                  'start_date', 'start_precision', 'end_date', 'end_precision',
                  'season_year', 'season', 'description', 'synopsis']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 2}),
            'synopsis': forms.Textarea(attrs={'rows': 2})
        }


class MediaUpdateForm(MediaCreateForm):
    pass


class MediaArtworkForm(forms.ModelForm):

    class Meta:
        model = MediaArtwork
        fields = ['image']


MediaArtworkFormset = forms.models.inlineformset_factory(Media, MediaArtwork, form=MediaArtworkForm,
                                                         extra=1, can_delete=True)

animesuki/media/api/views.py
"""AnimeSuki Media API Viewsets"""

from rest_framework import generics

from ..models import Media, MediaArtwork

from .serializers import MediaSerializer, MediaDetailSerializer, MediaArtworkSerializer


class MediaListAPIView(generics.ListAPIView):
    queryset = Media.objects.all()
    serializer_class = MediaSerializer
    permission_classes = ()


class MediaRetrieveAPIView(generics.RetrieveAPIView):
    queryset = Media.objects.all()
    serializer_class = MediaDetailSerializer
    permission_classes = ()


class MediaArtworkListAPIView(generics.ListAPIView):
    queryset = MediaArtwork.objects.all()
    serializer_class = MediaArtworkSerializer
    permission_classes = ()


class MediaArtworkRetrieveAPIView(generics.RetrieveAPIView):
    queryset = MediaArtwork.objects.all()
    serializer_class = MediaArtworkSerializer
    permission_classes = ()

animesuki/media/views.py
"""AnimeSuki Media views"""

from django.views.generic import DetailView, CreateView, UpdateView

from animesuki.core.views import PermissionMessageMixin, ArtworkActiveViewMixin, CanonicalDetailViewMixin
from animesuki.history.views import HistoryFormViewMixin, HistoryFormsetViewMixin

from .models import Media
from .forms import MediaCreateForm, MediaUpdateForm, MediaArtworkForm, MediaArtworkFormset


class MediaDetailView(CanonicalDetailViewMixin, DetailView):
    template_name = 'media/detail.html'
    model = Media


class MediaCreateView(PermissionMessageMixin, HistoryFormViewMixin, CreateView):
    permission_required = 'media.add_media'
    template_name = 'media/create.html'
    form_class = MediaCreateForm
    model = Media

    def get_success_url(self):
        return self.object.get_absolute_url('media:update')


class MediaUpdateView(PermissionMessageMixin, HistoryFormViewMixin, UpdateView):
    permission_required = 'media.change_media'
    template_name = 'media/update.html'
    form_class = MediaUpdateForm
    model = Media

    def get_success_url(self):
        return self.object.get_absolute_url('media:update')


class MediaArtworkView(PermissionMessageMixin, ArtworkActiveViewMixin, HistoryFormsetViewMixin, UpdateView):
    permission_required = 'media.change_mediaartwork'
    permission_denied_message = 'To be able to upload artwork you need to be a Contributor'
    template_name = 'media/artwork.html'
    form_class = MediaArtworkForm
    formset_class = MediaArtworkFormset
    model = Media

    def get_success_url(self):
        return self.object.get_absolute_url('media:artwork')

templates/media/_menu.html
{% load animesuki %}
<div class="btn-group align-self-center d-block ml-auto">
    <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle" data-toggle="dropdown"><i class="fas fa-cog"></i> Options</button>
    <div class="dropdown-menu dropdown-menu-right">
        {% if perms.media.change_media %}
            <a href="{% get_absolute_url media 'media:update' %}" class="dropdown-item"><i class="fas fa-pencil-alt fa-fw"></i> Edit</a>
        {% endif %}
        {% if perms.media.change_mediaartwork %}
            <a href="{% get_absolute_url media 'media:artwork' %}" class="dropdown-item"><i class="fas fa-file-image fa-fw"></i> Artwork</a>
        {% endif %}
        {% if perms.media.add_media %}
            <div class="dropdown-divider"></div>
            <a href="{% url 'media:create' 'media' %}" class="dropdown-item"><i class="fas fa-plus fa-fw"></i> Create</a>
        {% endif %}
    </div>
</div>

templates/media/artwork.html
{% extends 'base.html' %}
{% load animesuki history %}

{% block head_title %}{{ media.title }} Artwork | {{ media.get_media_type_display }} | AnimeSuki{% endblock head_title %}

{% block content %}
    <div class="d-flex flex-wrap">
        <h1>{{ media.title }} <span class="text-muted">Artwork</span></h1>
        {% if perms.media %}{% include 'media/_menu.html' with media=media perms=perms only %}{% endif %}
    </div>
    <form action="{% get_absolute_url media 'media:artwork' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {% include 'core/forms/_formset_artwork.html' with formset=form object=media comment_form=comment_form only %}
	    <div class="form-group row">
		    <div class="col-sm-2"></div>
		    <div class="col-sm-10">
                <button type="submit" class="btn btn-primary"><i class="fas fa-save fa-fw"></i> Save</button>
                <a href="{{ media.get_absolute_url }}" class="btn btn-outline-secondary ml-2"><i class="fas fa-undo fa-fw"></i> Back</a>
            </div>
        </div>
    </form>
    {% history_list_related media form.model %}
{% endblock content %}

templates/media/create.html
{% extends 'base.html' %}
{% load animesuki %}

{% block head_title %}Create Media | AnimeSuki{% endblock head_title %}

{% block content %}
    {% block content_title %}<h1><span class="text-muted">Create</span> Media</h1>{% endblock content_title %}
    <p>Leave unknown fields blank.</p>
    <form action="{% block form_url %}{% url 'media:create' 'media' %}{% endblock form_url %}" method="post">
        {% csrf_token %}
        {% include 'core/forms/_head.html' with form=form only %}
        {% for field in form.visible_fields %}
            {% if field in form|subset:'media_type,sub_type,status,is_adult,episodes,duration,volumes,chapters,start_date,start_precision,end_date,end_precision,season_year,season' %}
                {% if field == form.media_type %}
                    {% include 'core/forms/_row.html' with fields=form|subset:'media_type,sub_type,status,is_adult' label='Type / Status' label_css='col-sm-2' field_css='col-sm-2,col-sm-3,col-sm-3,col-sm-2' only %}
                {% elif field == form.episodes %}
                    {% include 'core/forms/_row.html' with fields=form|subset:'episodes,duration' label='Episodes / Duration' label_css='col-sm-2' field_css='col-sm-5,col-sm-5' only %}
                {% elif field == form.volumes %}
                    {% include 'core/forms/_row.html' with fields=form|subset:'volumes,chapters' label='Volumes / Chapters' label_css='col-sm-2' field_css='col-sm-5,col-sm-5' only %}
                {% elif field == form.start_date %}
                    {% include 'core/forms/_row.html' with fields=form|subset:'start_date,start_precision' label=form.start_date.label label_css='col-sm-2' field_css='col-sm-7,col-sm-3' only %}
                {% elif field == form.end_date %}
                    {% include 'core/forms/_row.html' with fields=form|subset:'end_date,end_precision' label=form.end_date.label label_css='col-sm-2' field_css='col-sm-7,col-sm-3' only %}
                {% elif field == form.season %}
                    {% include 'core/forms/_row.html' with fields=form|subset:'season,season_year' label=form.season.label label_css='col-sm-2' field_css='col-sm-5,col-sm-5' only %}
                {% endif %}
            {% else %}
                {% include 'core/forms/_field.html' with field=field row_css='form-group row' label_css='col-sm-2' field_css='col-sm-10' only %}
            {% endif %}
        {% endfor %}
	    <div class="form-group row">
		    <div class="col-sm-2"></div>
		    <div class="col-sm-10">
                <button type="submit" class="btn btn-primary"><i class="fas fa-save fa-fw"></i> Save</button>
                {% block form_buttons %}{% endblock form_buttons %}
            </div>
        </div>
    </form>
{% endblock content %}

templates/media/detail.html
{% extends 'base.html' %}
{% load animesuki %}

{% block head_title %}{{ media.title }} | {{ media.get_media_type_display }} | AnimeSuki{% endblock head_title %}

{% block meta %}
    <link rel="canonical" href="{% build_absolute_uri request media %}">
{% endblock %}

{% block content %}
    <div class="d-flex flex-wrap">
        <h1>{{ media.title }}</h1>
        {% if perms.media %}{% include 'media/_menu.html' with media=media perms=perms only %}{% endif %}
    </div>
    <div class="container"><div class="row">
        <div class="col-md-4 order-md-12 pr-md-0">
            {% if media.artwork_active %}
                <img src="{% call_method media.artwork_active 'get_image_url' '352w' %}" srcset="{% for size in media.artwork.get_image_sizes %}{% call_method media.artwork_active 'get_image_url' size %} {{ size }}{% if not forloop.last %}, {% endif %}{% endfor %}"  sizes="(max-width: 319px) 100vw, (max-width: 767px) 528px, (max-width: 1199px) 292px, 352px" class="img-fluid rounded" alt="{{ media.artwork_active }}" />
            {% endif %}
        </div>
        <div class="col-md-8 order-md-1">
{% with r='row py-1' h='col-lg-2 col-sm-3 pl-sm-2 font-weight-bold' d='col-lg-10 col-sm-9' %}
    <div class="{{ r }}">
        <div class="{{ h }}">Type</div>
        <div class="{{ d }}">{{ media.get_sub_type_display }}{% if media.is_adult %} (R-18){% endif %}{% spaceless %}
            {% if media.media_type == media.Type.ANIME and media.sub_type != media.SubType.MOVIE or media.episodes > 1 %}
                , {% if media.episodes is not None %}<span class="text-nowrap">{{ media.episodes }} episode{{ media.episodes|pluralize }}</span>{% else %}unknown number of episodes{% endif %}
            {% elif media.media_type != media.Type.ANIME and media.volumes > 1 %}
                , <span class="text-nowrap">{{ media.volumes }} volume{{ media.volumes|pluralize }}</span>
            {% elif media.media_type != media.Type.ANIME and media.chapters > 1 %}
                , <span class="text-nowrap">{{ media.chapters }} chapter{{ media.chapters|pluralize }}</span>
            {% elif media.media_type != media.Type.ANIME %}
                , unknown number of chapters
            {% endif %}
        {% endspaceless %}</div>
    </div>
    <div class="{{ r }}">
        <div class="{{ h }}">Status</div>
        <div class="{{ d }}">{{ media.get_status }}</div>
    </div>
    <div class="{{ r }}">
        <div class="{{ h }}">Vintage</div>
        <div class="{{ d }}">
            {% if media.start_date is not None %}<span class="text-nowrap">{{ media.start_date|date:'SHORT_DATE_FORMAT'|date_precision:media.start_precision }}</span>{% else %}?{% endif %}
            {% if media.start_date != media.end_date %}
                ~ {% if media.end_date is not None %}<span class="text-nowrap">{{ media.end_date|date:'SHORT_DATE_FORMAT'|date_precision:media.end_precision }}</span>{% else %}?{% endif %}
            {% endif %}
        </div>
    </div>
    {% if media.media_type == media.Type.ANIME and media.season_year %}
    <div class="{{ r }}">
        <div class="{{ h }}">Season</div>
        <div class="{{ d }}">
        {% if media.season %}
            {{ media.get_season_display }} {{ media.season_year }}
        {% else %}
            {{ media.season_year }}
        {% endif %}
        </div>
    </div>
    {% endif %}
    {% if media.description %}
    <div class="{{ r }}">
        <div class="{{ h }}">Description</div>
        <div class="{{ d }}">{{ media.description }}</div>
    </div>
    {% endif %}
    {% if media.synopsis %}
    <div class="{{ r }}">
        <div class="{{ h }}">Synopsis</div>
        <div class="{{ d }}">{{ media.synopsis }}</div>
    </div>
    {% endif %}
{% endwith %}
        </div>
    </div></div>
{% endblock content %}

templates/media/update.html
{% extends 'media/create.html' %}
{% load animesuki history %}

{% block head_title %}Edit {{ media.title }} | {{ media.get_media_type_display }} | AnimeSuki{% endblock head_title %}

{% block content_title %}
    <div class="d-flex flex-wrap">
        <h1><span class="text-muted">Edit</span> {{ media.title }}</h1>
        {% if perms.media %}{% include 'media/_menu.html' with media=media perms=perms only %}{% endif %}
    </div>
{% endblock content_title %}

{% block form_url %}{% get_absolute_url media 'media:update' %}{% endblock form_url %}

{% block form_buttons %}<a href="{{ media.get_absolute_url }}" class="btn btn-outline-secondary ml-2"><i class="fas fa-undo fa-fw"></i> Back</a>{% endblock form_buttons %}

{% block content %}
    {{ block.super }}
    {% history_list media %}
{% endblock content %}